apiVersion: v1
kind: ReplicationController
metadata:
  name: mysqlcrm-master
  labels:
    name: mysqlcrm-master
spec:
  replicas: 1
  selector:
    name: mysqlcrm-master
  template:
    metadata:
      labels:
        name: mysqlcrm-master
    spec:
      containers:
      - name: master
        image: 192.168.0.236:8889/wangsj/mysql5.6-master:3.1
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 'dongjingroot'
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysqlcrm-master-data
      volumes:
      - name: mysqlcrm-master-data
        persistentVolumeClaim:
          claimName: mysqlcrm-master
