apiVersion: v1
kind: ReplicationController
metadata:
  name: mycat
spec:
  replicas: 1
  selector:
    name: mycat
  template:
    metadata:
      labels:
        name: mycat
    spec:
      containers:
        - name: mycat
          image: 192.168.0.236:9001/wangsj/mycat:0.4
          ports:
          - containerPort: 8066
          ports:
          - containerPort: 9066
