apiVersion: v1
kind: Service
metadata:
  name: mycat
spec:
  ports:
    - port: 8066
      targetPort: 8066
      protocol: TCP
      name: "8066"
    - port: 9066
      targetPort: 9066
      protocol: TCP
      name: "9066"
  type: NodePort
  selector:
    name: mycat
