apiVersion: v1
kind: Service
metadata:
  name: djcps-mongodb-com
  labels:
    app: {{ template "mongodb.name" . }}
    chart: {{ template "mongodb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  type: NodePort
  selector:
    app: {{ template "mongodb.name" . }}
    release: {{ .Release.Name }}
---
