apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-oabi-slave
  labels:
    name: mysql-oabi-slave
spec:
  replicas: 1
  selector:
    name: mysql-oabi-slave
  template:
    metadata:
      labels:
        name: mysql-oabi-slave
    spec:
      containers:
      - name: master
        image: 192.168.0.236:8889/wangsj/mysql5.6-slave:3.1
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 'dongjingroot'
        - name: MYSQL_MASTER_HOST
          value: 'mysql-oabi-master'
        - name: MYSQL_MASTER_SERVICE_HOST
          value: 'mysql-oabi-master'
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-oabi-slave-data
      volumes:
      - name: mysql-oabi-slave-data
        persistentVolumeClaim:
          claimName: mysql-oabi-slave
