apiVersion: v1
kind: Service
metadata:
  name: mysqlcrm-slave
  labels:
    name: mysqlcrm-slave
spec:
  ports:
  - port: 3306
    targetPort: 3306
  type: NodePort
  selector:
    name: mysqlcrm-slave
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysqlcrm-slave
spec:
  storageClassName: nfs-dynamic-class1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
