apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
  - name: rabbitmq
    port: 5672
    targetPort: 15672
  selector:
     app: rabbitmq
  type: NodePort
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbitmq
spec:
  storageClassName: nfs-dynamic-class1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
