apiVersion: v1
kind: Service
metadata:
  name: redis-single
  labels:
    name: redis-single
spec:
  ports:
  - port: 6379
    targetPort: 6379
  type: NodePort
  selector:
    name: redis-single
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-single
spec:
  storageClassName: nfs-dynamic-class1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
